# From https://github.com/OliverMKing/javascript-release-workflow/blob/main/.github/workflows/release-pr.yml
name: Create release PR

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Define release version (ex: v1, v2, v3)'
        required: true
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if remote branch exists
        env:
          BRANCH: releases/${{ github.event.inputs.release }}
        run: |
          echo "##[set-output name=exists;]$(echo $(if [[ -z $(git ls-remote --heads origin ${BRANCH}) ]]; then echo false; else echo true; fi;))"
        id: extract-branch-status
        # these two only need to occur if the branch exists
      - name: Checkout proper branch
        if: ${{ steps.extract-branch-status.outputs.exists == 'true' }}
        env:
          BRANCH: releases/${{ github.event.inputs.release }}
        run: git checkout ${BRANCH}
      - name: Set git user
        run: |
          git config --global user.email "bastien.jeannelle@gmail.com"
          git config --global user.name "Sonlis"
      - name: Merge
        if: ${{ steps.extract-branch-status.outputs.exists == 'true' }}
        env:
          BRANCH: releases/${{ github.event.inputs.release }}
        run: |
          git fetch origin main:main
          git checkout -b tmp origin/main
          git merge -s ours ${BRANCH}
          git checkout ${BRANCH}
          git rm -r node_modules --ignore-unmatch
          git merge tmp
          git branch -D tmp
      - name: Install ncc
        run: npm i -g @vercel/ncc
      - name: Install packages
        run: |
          rm -rf node_modules/
          npm install --no-bin-links
      - name: Build
        run: ncc build src/run.ts -o lib
      - name: Remove lib from gitignore
        continue-on-error: true
        run: |
          sed -i '/lib/d' ./.gitignore
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: releases/${{ github.event.inputs.release }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: Bastien Jeannelle <bastien.jeannelle@gmail.com>
          author: Bastien Jeannelle <bastien.jeannelle@gmail.com>
          token: ${{ secrets.RELEASE_TOKEN }}
          commit-message: Add node modules and compiled JavaScript from main
          title: ${{ github.event.inputs.release }} new release
          base: releases/${{ github.event.inputs.release }}
          delete-branch: true
